/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class pl_edu_pwr_discreteconvolutionfunction_DiscreteConvolutionFunction */

#ifndef _Included_pl_edu_pwr_discreteconvolutionfunction_DiscreteConvolutionFunction
#define _Included_pl_edu_pwr_discreteconvolutionfunction_DiscreteConvolutionFunction
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     pl_edu_pwr_discreteconvolutionfunction_DiscreteConvolutionFunction
 * Method:    calculateDiscreteConvolutionFunctionNative
 * Signature: ([[I[[I)[[I
 */
JNIEXPORT jobjectArray JNICALL Java_pl_edu_pwr_discreteconvolutionfunction_DiscreteConvolutionFunction_calculateDiscreteConvolutionFunctionNative
  (JNIEnv *, jobject, jobjectArray, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
